name: build-and-push
on:
  push:
    branches: [release]
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            VITE_SERVER_URL=
          tags: |
            ghcr.io/zfdupont/huskies-client:latest
            ghcr.io/zfdupont/huskies-client:${{ github.sha }}
